const fs = require('fs');
const path = require('path');

// Load the full documentation
// this `doc.json` file is generated by running jsdoc in the strudel repo (renamed to "strudel_doc.json" here)
const docPath = path.join(__dirname, 'strudel_doc.json');
if (!fs.existsSync(docPath)) {
    console.error('doc.json not found. Please run "npm run jsdoc-json" in the strudel directory first.');
    process.exit(1);
}

const docData = JSON.parse(fs.readFileSync(docPath, 'utf8'));

// Extract essential completion data
const completionData = {
    functions: [],
    lastGenerated: new Date().toISOString()
};

function isValidDoc(doc) {
    return doc.name && 
           !doc.name.startsWith('_') && 
           doc.kind !== 'package' &&
           doc.kind !== 'module' &&
           !hasExcludedTags(doc);
}

function hasExcludedTags(doc) {
    const excludedTags = ['superdirtOnly', 'noAutocomplete'];
    return excludedTags.some(tag => 
        doc.tags?.some(t => t.title === tag)
    );
}

const seen = new Set();

for (const doc of docData.docs) {
    if (!isValidDoc(doc)) continue;

    const names = [doc.name];
    if (doc.synonyms) {
        names.push(...doc.synonyms);
    }

    for (const name of names) {
        if (name && !seen.has(name)) {
            seen.add(name);
            
            const entry = {
                name: name,
                description: doc.description || '',
                params: doc.params ? doc.params.map(p => ({
                    name: p.name,
                    type: p.type?.names?.join(' | ') || 'any',
                    description: p.description || ''
                })) : [],
                examples: doc.examples || [],
                synonyms: doc.synonyms || [],
                originalName: doc.name
            };

            completionData.functions.push(entry);
        }
    }
}

// Sort functions alphabetically
completionData.functions.sort((a, b) => a.name.localeCompare(b.name));

// Write optimized completion data
const outputPath = path.join(__dirname, '..', 'src', 'strudelCompletions.json');
fs.writeFileSync(outputPath, JSON.stringify(completionData, null, 2));

console.log(`Generated completion data for ${completionData.functions.length} functions`);
console.log(`Saved to: ${outputPath}`);

// Calculate size reduction
const originalSize = fs.statSync(docPath).size;
const newSize = fs.statSync(outputPath).size;
console.log(`Size reduction: ${originalSize} bytes -> ${newSize} bytes (${Math.round((1 - newSize/originalSize) * 100)}% smaller)`);